### ISSUE TITLE
Fix work on Xiaomi Mi Note 10

### ISSUE THREAD

**Issue by edge1** [eszdman/PhotonCamera#1]
Run app and get this. After 30s or so, app exits.

![Screenshot_2020-05-26-10-47-21-583_com eszdman photoncamera](https://user-images.githubusercontent.com/20436953/82900171-cb06fc00-9f64-11ea-9e54-0965071ef2ac.jpg)

![Screenshot_2020-05-26-15-01-43-713_com android settings](https://user-images.githubusercontent.com/20436953/82900165-c9d5cf00-9f64-11ea-939a-75cce7c63677.jpg)

**Comment by assasinfil** [comment]
Need logs from logcat or matlog(crash log).

**Comment by edge1** [comment]
> Need logs from logcat or matlog(crash log).
Где(как) его получить?

**Comment by edge1** [comment]
[2020-05-27-14-39-37.txt](https://github.com/eszdman/PhotonCamera/files/4688552/2020-05-27-14-39-37.txt)
