### ISSUE TITLE
Pixel 2 XL Images too dark, Incorrect ISO and Shutter Speed Calculation

### ISSUE THREAD

**Issue by snajdovski** [eszdman/PhotonCamera#12]
**Describe the bug**
Without any manual changing of ISO and Shutter Speed the pictures are underexposed by 2 stops 

**To Reproduce**
1. Install latest APK
2. Take a Picture
3. Look at the Picture

**Expected behavior**
Better Exposure

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10 (QQ3A.200805.001)

**Comment by eszdman** [comment]
Fixed with different compressor setting
