### ISSUE TITLE
Android 11 Beta 3 Pixel 2 XL [CRASH]

### ISSUE THREAD

**Issue by snajdovski** [eszdman/PhotonCamera#15]
**Describe the bug**
The bug occurs when taking a picture or more precisely when its time to process.

**To Reproduce**
1. Have Pixel 2 XL with Android 11 (not sure about other Android 11 devices)
2. Try to take a picture without changing the settings
3.Crash

**Expected behavior**
A photo in Gallery and no Crash

**Screenshots**
No need for screenshots.

**Logs**
[log_v_hdrx_on_default_settings_latest_commit.log](https://github.com/eszdman/PhotonCamera/files/5180284/log_v_hdrx_on_default_settings_latest_commit.log)
[log_v_pinned_apk.log](https://github.com/eszdman/PhotonCamera/files/5180285/log_v_pinned_apk.log)
**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11 Beta 3 (RPB3.200720.005)

**Additional context**
With GPU alignment doesn't crash.

**Comment by Dimoon12** [comment]
Pixel 4xl same
