### ISSUE TITLE
Wrong camera preview proportions

### ISSUE THREAD

**Issue by UAVXP** [eszdman/PhotonCamera#2]
**Describe the bug**
Preview image is not proportioned like it should be in portrait mode. The camera view is just put in a square

**To Reproduce**
1. Put your smartphone in the portrait mode (either manually or automatically)
2. Open an app
3. Look at the preview

**Expected behavior**
Well proportioned preview image in portrait mode

**Screenshots**
Portrait orientation:
![image](https://user-images.githubusercontent.com/3075683/82915280-32c74200-9f79-11ea-9a11-9e697fb76fb6.png)
Landscape orientation:
![image](https://user-images.githubusercontent.com/3075683/82915303-3955b980-9f79-11ea-89d7-cd9fd19ca528.png)

**Smartphone (please complete the following information):**
 - Device: ASUS ZenFone Max Pro M1
 - OS: Android 9
 - Browser: Google Chrome
 - Version: 1.0

**Comment by assasinfil** [comment]
Fixed
