### ISSUE TITLE
Share method improvements

### ISSUE THREAD

**Issue by rancidfrog** [eszdman/PhotonCamera#23]
When sharing from photon app after taking a photograph, the multiple share optiins do not show:

Photon app share implementation:
![](https://i.imgur.com/1bYoyRC.png)

The share is general, recent optiims not shown

Default camera app, and other apps as well, share implementation:
![](https://i.imgur.com/64ohsGE.png)

Not only can you share by apps, but recent options, i.e. whatsapp/instagram/other apps, are included

**Comment by eszdman** [comment]
Try using this type of share
I am using android 10 and recent applications working, most frequent applications on top

**Comment by rancidfrog** [comment]
@vibhorSrv
Has anything been changed?
In recent android versions there is the ability to share not only with most used apps, but also with most recent sent contact. Which was what I was referring to, this way you can send directly to contact or group without selecting app and then contact.

**Comment by vibhorSrv** [comment]
what you are referring to is achieved by using "android.intent.action.CHOOSER". and yes it has been implemented  recently.
https://git.io/JtvFV
