### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by hshsa** [eszdman/PhotonCamera#28]
Привет, очень медленный автофокус и он не работает по касанию. 

Galaxy s6 edge+, андроид 10 (ради этой камеры обновился).

А результат в раве - просто огонь, намного лучше гкама. Скорость выравнивания - выше всяких похвал, так держать!

**Comment by eszdman** [comment]
Нужен скриншот работы автофокуса с включёнными дебаг данными, лучше видео
