### ISSUE TITLE
Info about 32bit devices

### ISSUE THREAD

**Issue by ilmich** [eszdman/PhotonCamera#40]
Hi,

I'm testing this app on my Oneplus Nord and looks very promising (I don't like closed source app, but for now GCam is the only really usable app).
But I've another question. It's possible to build a 32bit version!?
I've another oneplus one(not really bad hardware, but very bad software available)

Thanks in advance
Michele

**Comment by eszdman** [comment]
I think in the future it is possible to make a version for armv7, but it will not be supported due to the fact that it significantly increases the weight of the application.

**Comment by eszdman** [comment]
Should be fixed for armv7 now, you can build from dev branch
Use any alignment except cpu
