### ISSUE TITLE
How to change ratio preview camera

### ISSUE THREAD

**Issue by vuhiepth7** [eszdman/PhotonCamera#42]
- I try to change ratio of camera. Ex: 1:1 in layoutviewfinder (AutoFitPreviewView). Wrong Preview!. Best Preview with ratio 3:4, 9:16  Can you support  me, please. Thanks you
- How to create preview by mode centercrop. Full Screen for ratio: .9:16

**Comment by snajdovski** [comment]
Photon Uses Camera 2 API to capture photos, the official Google documentation could help you:
https://developer.android.com/training/camerax/preview
https://developer.android.com/training/camera2
