### ISSUE TITLE
OP5: Unsupported device and crashing

### ISSUE THREAD

**Issue by mizzunet** [eszdman/PhotonCamera#45]
**Describe the bug**
Photon camera is crashing on OnePlus 5 also shows a toast that it's unsupported device. 

**To Reproduce**
1. Open Photon Camera
2. Capture photo from either front/back camera
3. See it's crashing on OnePlus 5

**Expected behavior**
Should save photo rather than ctashing.

**Screenshots**

**Logs**
https://nekobin.com/boyagufoga

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 11, RevengeOS
 - Browser: Bromite
 - Version: Version 0.72

**Additional notes**
May I know what are it's requirements? I know that OnePlus 5 isn't in Supported List, can it make working somehow?

**Comment by VildaTech** [comment]
PhotonCamera have issues with following things.

Android 11
You need camera2api enable
Devices on Android 10, 9... have works much better.

I have OnePlus 6 with stock OxygenOS based on Android 10 and PhotonCamera works.

**Comment by mizzunet** [comment]
> PhotonCamera have issues with following things.
> 
> Android 11
> You need camera2api enable
> Devices on Android 10, 9... have works much better.
> 
> I have OnePlus 6 with stock OxygenOS based on Android 10 and PhotonCamera works.

Camera2API has already been enabled, I guess, as GCam works fine. 
![Screenshot_20210411-194407](https://user-images.githubusercontent.com/10193999/114307729-c4f30e80-9a95-11eb-8178-c3bca0216879.png)
![Screenshot_20210411-194359](https://user-images.githubusercontent.com/10193999/114307731-c7556880-9a95-11eb-9a1e-e1a7433eb3c3.png)

Any chance for some workaround for PhotoCamera working Android 11?

**Comment by VildaTech** [comment]
Probably in the future, but PhotonCamera on Android 11 have issues.
You can try GPU align method, in some cases could help.

**Comment by eszdman** [comment]
Fixed
