### ISSUE TITLE
newer build apk availability

### ISSUE THREAD

**Issue by abdulhakam** [eszdman/PhotonCamera#67]
hi, It would be better if apks of latest builds are available via f-droid or downloadable apk release, so that many more people can test it. I'm currently using 0.72 whereas I cannot find 0.81(?),
using tecno LD7 and it doesn't work.  When I start the app it tells device not supported and when I take a picture it says Failed

**Comment by KillerInk** [comment]
> hi, It would be better if apks of latest builds are available via f-droid or downloadable apk release, so that many more people can test it. I'm currently using 0.72 whereas I cannot find 0.81(?),

check this
https://github.com/eszdman/PhotonCamera/releases/tag/v0.8

**Comment by abdulhakam** [comment]
Thanks
