### ISSUE TITLE
More informations about technical which libHDRX use

### ISSUE THREAD

**Issue by unknow-dev** [eszdman/PhotonCamera#7]
Hi @eszdman, Can you share some informations about the technology applied in libHDRX.so?

Thanks.

**Comment by eszdman** [comment]
Hello, we use the library on halide in order to pyramidal align and merge the images that the camera receives, this can be seen from the Wrapper.java source.
If you wish, you can replace this library with your implementation.

**Comment by unknow-dev** [comment]
Thanks for your reply.
It seems you use the same approach like  https://github.com/timothybrooks/hdr-plus, right?

**Comment by eszdman** [comment]
Yes, that's right, based on these alignment algorithm

**Comment by unknow-dev** [comment]
I was make a comparison between your HDRX raw output and "hdr-plus" raw output (from same raws step input), I realize that your results are less noise than "hdr-plus" output.

**Comment by eszdman** [comment]
Hdplus implementation is not designed for mobile dng and CPU's and requires tuning

**Comment by unknow-dev** [comment]
And another issue that I see it affects both your module and hdr-plus, if there is an object moving between frames, the result have some small blocks overlap.

**Comment by eszdman** [comment]
Robust model requires adjustments, this is fixed in recent dev updates

**Comment by unknow-dev** [comment]
Thanks for your infomations :D
One more question, Do you have any plan to make some PR to  https://github.com/timothybrooks/hdr-plus to improve it results, that repo look like be still maintained to make it better or are your technologies is private?

**Comment by eszdman** [comment]
Perhaps later the old library will be opened as a separate repository, as the main algorithms will be redone to work on GPU.
