### ISSUE TITLE
32 bit device support

### ISSUE THREAD

**Issue by JohnRTitor** [eszdman/PhotonCamera#72]
I have a device with 32 bit CPU (Redmi 9a) (yes Xiaomi still makes 32 bit devices). My phone does not support gcam and would love to use Photoncamera instead, thanks!

**Comment by eszdman** [comment]
Compile for yourself or download from night builds: https://photoncamera-night-builds.e7.by/

**Comment by JohnRTitor** [comment]
> Compile for yourself or download from night builds: https://photoncamera-night-builds.e7.by/

Those armv7 builds lack important libraries like libHDRX, libomp and they don't work.
