### ISSUE TITLE
Images with bright backgrounds process way to underexposed.

### ISSUE THREAD

**Issue by dportuesi-pzm** [eszdman/PhotonCamera#84]
**Describe the bug**
I've noticed that sometimes when I take a picture it is terribly underexposed. Below I have a link of a pic with photon camera and with the generic android camera. I've noticed its especially prevalent when the background is light but the foreground is dark.

Its worth noting, the preview for the image shows perfectly normal amounts of exposure, the issue only occurs when viewer the image AFTER it processes.

PhotonCamera
![image](https://user-images.githubusercontent.com/102051874/178165288-be8866b6-3312-4cae-ae62-5a307972fcee.png)

AOSP Camera
![image](https://user-images.githubusercontent.com/102051874/178165296-61e13bcb-2e6c-4c8c-937b-52a0f1e66ec4.png)

PhotonCamera
![image](https://user-images.githubusercontent.com/102051874/178165336-3d63933e-ee91-4c2c-8906-5e6f83d9841d.png)

**To Reproduce**
Open camera app,
leave default settings (Auto focus mode: auto, Watermark Off (only default changed), HDRX Noise Reduction ON).
I'm happy to take a screenshot of any setting if necessary.

**Expected behavior**
The photo look more like AOSP camera where a bright background doesn't darken the foreground to the point of being drastically underexposed. 

**Screenshots**
See Above

**Logs**
Available upon request, not sure what is specifically needed to debug.

**Smartphone (please complete the following information):**
 - Device: OnePlus7ProNR
 - OS: YAAP (Yet Another AOSP Project) (Android 12)
 - Browser: Brave (chromium based)
 - Version: 0.8.14660

**Additional context**
None.

**Comment by eszdman** [comment]
This problem is not related to exposure, but rather to image processing, so it is not a described problem
