### ISSUE TITLE
Supported devices?

### ISSUE THREAD

**Issue by Efreak** [eszdman/PhotonCamera#88]
I saw in an issue that Android 11 (and presumably newer) is unsupported. This should be mentioned in the readme, along with a list of devices that are explicitly supported/tested by developer. Known issues on working but unsupported devices would also be helpful.

**Comment by eszdman** [comment]
Latest dev working perfectly on android 13

**Comment by Tarek-Hasan** [comment]
@eszdman you should close resolved issues like this.
